# Generated by Django 4.2.25 on 2025-11-18 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import posts.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "club_name",
                    models.CharField(max_length=100, verbose_name="동아리/팀 이름"),
                ),
                (
                    "application_months",
                    models.JSONField(
                        help_text='배열 형태로 지원이 가능한 월을 입력하세요. 예: ["2월", "3월"]',
                        validators=[posts.models.validate_month_list],
                        verbose_name="지원 기간 (월)",
                    ),
                ),
                (
                    "activity_months",
                    models.JSONField(
                        help_text='배열 형태로 활동이 이루어지는 월을 입력하세요. 예: ["2월", "3월", "4월"]',
                        validators=[posts.models.validate_month_list],
                        verbose_name="주요 활동 기간 (월)",
                    ),
                ),
                ("description", models.TextField(verbose_name="동아리 상세 설명")),
                (
                    "eligibility",
                    models.TextField(
                        blank=True,
                        help_text="예: 특정 학과, 특정 개발 레벨 이상 등",
                        verbose_name="신청 자격",
                    ),
                ),
                (
                    "recruitment_fields",
                    models.TextField(
                        help_text="예: 백엔드, 프론트엔드, 디자이너",
                        verbose_name="모집 분야",
                    ),
                ),
                (
                    "review_link",
                    models.URLField(
                        blank=True, null=True, verbose_name="이전 활동 후기 링크"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="게시글 공개 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="최근 수정일"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recruitment_posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "모집 공고",
                "verbose_name_plural": "모집 공고 목록",
                "db_table": "posts",
                "ordering": ["-created_at"],
            },
        ),
    ]
