# Generated by Django 4.2.25 on 2025-11-19 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "club_name",
                    models.CharField(max_length=100, verbose_name="동아리/팀 이름"),
                ),
                (
                    "homepage_link",
                    models.URLField(
                        blank=True, null=True, verbose_name="동아리/팀 홈페이지"
                    ),
                ),
                (
                    "application_months",
                    models.CharField(
                        blank=True,
                        help_text="미리 정의된 월 목록에서 선택하세요. (콤마로 구분된 코드)",
                        max_length=50,
                        verbose_name="지원 기간 (월)",
                    ),
                ),
                (
                    "activity_months",
                    models.CharField(
                        blank=True,
                        help_text="미리 정의된 월 목록에서 선택하세요. (콤마로 구분된 코드)",
                        max_length=50,
                        verbose_name="주요 활동 기간 (월)",
                    ),
                ),
                ("description", models.TextField(verbose_name="동아리 상세 설명")),
                (
                    "eligibility",
                    models.CharField(
                        blank=True,
                        help_text="미리 정의된 소속 코드 목록에서 다중 선택하세요. (콤마로 구분된 코드)",
                        max_length=100,
                        verbose_name="신청 자격 (소속)",
                    ),
                ),
                (
                    "recruitment_fields",
                    models.CharField(
                        help_text="미리 정의된 분야 코드 목록에서 다중 선택하세요. (콤마로 구분된 코드)",
                        max_length=100,
                        verbose_name="모집 분야",
                    ),
                ),
                (
                    "required_dev_levels",
                    models.CharField(
                        blank=True,
                        help_text="미리 정의된 레벨 코드 목록에서 다중 선택하세요. (콤마로 구분된 코드)",
                        max_length=100,
                        verbose_name="요구 개발 레벨",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="게시글 공개 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="최근 수정일"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recruitment_posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "모집 공고",
                "verbose_name_plural": "모집 공고 목록",
                "db_table": "posts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PostReviewLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "review_title",
                    models.CharField(max_length=100, verbose_name="후기 제목"),
                ),
                ("review_url", models.URLField(verbose_name="후기 링크")),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="posts.post",
                        verbose_name="모집 공고",
                    ),
                ),
            ],
            options={
                "verbose_name": "활동 후기 링크",
                "verbose_name_plural": "활동 후기 링크 목록",
            },
        ),
    ]
