# Generated by Django 4.2.25 on 2025-11-19 01:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="type",
            field=models.CharField(
                choices=[
                    ("CLUB", "동아리"),
                    ("EXTERNAL", "대외활동"),
                    ("BOOTCAMP", "부트캠프"),
                ],
                default="CLUB",
                help_text="모집하는 활동의 종류를 선택하세요.",
                max_length=10,
                verbose_name="활동 종류",
            ),
        ),
    ]
