# Generated by Django 4.2.25 on 2025-11-19 05:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_post_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="club_name",
            new_name="name",
        ),
    ]
