# Generated by Django 4.2.25 on 2025-11-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_rename_club_name_post_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="type",
            field=models.CharField(
                choices=[
                    ("club", "동아리"),
                    ("external", "대외활동"),
                    ("bootcamp", "부트캠프"),
                ],
                default="club",
                help_text="모집하는 활동의 종류를 선택하세요.",
                max_length=10,
                verbose_name="활동 종류",
            ),
        ),
    ]
