# Generated by Django 4.2.25 on 2025-11-18 04:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "username",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="아이디"
                    ),
                ),
                (
                    "nickname",
                    models.CharField(max_length=50, unique=True, verbose_name="닉네임"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="이메일"
                    ),
                ),
                (
                    "interest_field",
                    models.CharField(
                        choices=[
                            ("PM", "프로젝트/제품 관리 (PM)"),
                            ("DESIGN", "디자인"),
                            ("FRONTEND", "프론트엔드"),
                            ("BACKEND", "백엔드"),
                        ],
                        default="FRONTEND",
                        max_length=10,
                        verbose_name="관심분야",
                    ),
                ),
                (
                    "affiliation",
                    models.CharField(
                        choices=[
                            ("STUDENT", "대학생"),
                            ("GRADUATE", "졸업생"),
                            ("WORKER", "직장인"),
                        ],
                        default="STUDENT",
                        max_length=10,
                        verbose_name="소속",
                    ),
                ),
                (
                    "dev_level",
                    models.CharField(
                        choices=[
                            ("NOVICE", "초심자"),
                            ("INTERMEDIATE", "중급자"),
                            ("ADVANCED", "고급자"),
                        ],
                        default="NOVICE",
                        max_length=15,
                        verbose_name="개발 레벨",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="가입일"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to.",
                        related_name="custom_user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="custom_user_permissions_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자",
                "verbose_name_plural": "사용자 목록",
                "db_table": "users",
            },
        ),
    ]
