# Generated by Django 4.2.25 on 2025-11-19 00:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="interest_field",
            field=models.CharField(
                choices=[
                    ("PM", "기획"),
                    ("DESIGN", "디자인"),
                    ("FRONTEND", "프론트엔드"),
                    ("BACKEND", "백엔드"),
                    ("AI_ML", "AI/머신러닝"),
                ],
                default="FRONTEND",
                max_length=10,
                verbose_name="관심분야",
            ),
        ),
    ]
