# Generated by Django 4.2.25 on 2025-11-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_interest_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="affiliation",
            field=models.CharField(
                choices=[
                    ("STUDENT_CS", "대학생(전공)"),
                    ("STUDENT_NON_CS", "대학생(비전공)"),
                    ("GRADUATE", "졸업생"),
                    ("WORKER", "직장인"),
                    ("NON_MAJOR", "비전공자"),
                ],
                default="STUDENT_CS",
                max_length=20,
                verbose_name="소속",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="interest_field",
            field=models.CharField(
                choices=[
                    ("PM", "기획"),
                    ("DESIGN", "디자인"),
                    ("FRONTEND", "프론트엔드"),
                    ("BACKEND", "백엔드"),
                    ("AI_ML", "AI/머신러닝"),
                    ("EMBEDDED", "임베디드 SW"),
                    ("QA", "QA/테스팅"),
                    ("NETWORK", "네트워크/보안"),
                    ("ETC", "기타"),
                ],
                default="FRONTEND",
                max_length=15,
                verbose_name="관심분야",
            ),
        ),
    ]
