# Generated by Django 4.2.25 on 2025-11-18 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("CREATE", "게시글 생성 요청"),
                            ("UPDATE", "게시글 수정 요청"),
                        ],
                        max_length=10,
                        verbose_name="요청 유형",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="요청 제목")),
                ("content", models.TextField(verbose_name="요청 상세 내용")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기 중"),
                            ("approved", "승인됨"),
                            ("rejected", "거절됨"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="처리 상태",
                    ),
                ),
                (
                    "review_comment",
                    models.TextField(blank=True, verbose_name="검토 코멘트"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="요청 생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="최근 갱신일"),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="요청자",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="검토자",
                    ),
                ),
                (
                    "target_post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="related_requests",
                        to="posts.post",
                        verbose_name="대상 게시글",
                    ),
                ),
            ],
            options={
                "verbose_name": "관리자 요청",
                "verbose_name_plural": "관리자 요청 목록",
                "db_table": "admin_requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
