# Generated by Django 4.2.25 on 2025-11-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_requests", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "요청 처리중"),
                    ("done", "요청 처리됨"),
                    ("rejected", "거절됨"),
                ],
                default="processing",
                max_length=16,
                verbose_name="처리 상태",
            ),
        ),
    ]
