# Generated by Django 4.2.25 on 2025-11-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_requests", "0002_alter_adminrequest_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminrequest",
            name="request_type",
            field=models.CharField(
                choices=[
                    ("CREATE", "게시글 생성 요청"),
                    ("UPDATE", "게시글 수정 요청"),
                    ("FEEDBACK", "불편사항 건의"),
                ],
                max_length=10,
                verbose_name="요청 유형",
            ),
        ),
    ]
